### ISSUE TITLE
DatePicker: Unavailable dates are shown, select fail silently

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-js#19]
See below : 
<img width="1280" alt="capture d ecran 2017-09-29 a 18 27 54" src="https://user-images.githubusercontent.com/4426585/31025750-0df069d4-a544-11e7-9845-c9257c03a04b.png">

**Comment by alexsegura** [comment]
I think this is fixed now.

**Comment by Atala** [comment]
Yes it is fixed by coopcycle/coopcycle-web@84a9d618abf7306b589a50e6691917a9cfd778c9 I think.
